### ISSUE TITLE
Question regarding init

### ISSUE THREAD

**Issue by HarrisJT** [sonaye/react-with-analytics#3]
Why do you call init in your app.js and not on the "componentDidMount" of WithAnalytics? Seems like you would want to do network requests from there, right?

**Comment by sonaye** [comment]
The init function loads the analytics script from Google, see the source [here](https://github.com/react-ga/react-ga/blob/master/src/utils/loadGA.js), which allows for issuing network requests after that. Ideally you would want to load all the scripts at the beginning.

Calling any of the tracking methods `trackPage, trackUser, trackEvent` issues the network requests, they should be used within the component, CDM or any other place.

**Comment by HarrisJT** [comment]
Well that script _does_ make a network request.

**Comment by sonaye** [comment]
True, but it's for loading the assets, it replaces `<script />` tag, you can put it CDM I don't think it's an issue.
