### ISSUE TITLE
Page unresponsive

### ISSUE THREAD

**Issue by afilp** [sonaye/react-with-analytics#5]
I followed your example but the app does not start, because I get a "Page unresponsive" message:

![image](https://user-images.githubusercontent.com/7850073/45577204-7d775800-b883-11e8-9c84-c5951adab166.png)

I use React Router v4.
I also use the HashRouter.

Any ideas? Thanks!

**Comment by sonaye** [comment]
Can you share your full code? and where do you see this meesgae excatly, is this a component within your app?

**Comment by afilp** [comment]
@sonaye Sorry for the delayed response, it is fixed.

It seems that I had forgotten the old `ReactGA.initialize('UA-XXXXXXX-1');` code while i was also using the new `initAnalytics('UA-XXXXXXX-1');` code.

This was most likely the cause of the trouble since when removing the old code the page worked.

Thanks!

**Comment by afilp** [comment]
Sorry for the delay, I thought it was solved by my side, but it wasn't.

See my code here:

```
import { Component } from '../javascript/extLibs/http_github.com_borisyankov_DefinitelyTyped_raw_master_react_react';
import React from "react";
import ReactDOM from 'react-dom';
import { Redirect, withRouter } from 'react-router';
import withAnalytics, { initAnalytics } from 'react-with-analytics';

/* OTHER NON-RELATED CODE HERE, FOR WINDOW VARIABLES, ETC. */

showApp();

function showApp() {

    const Root = () => (
        <div className="flex-column-1">
            <Route exact path="/"
                   render={() => <Redirect to={{/*...location, */ pathname: `/${process.env.APP}`}} />} />
            <Route
                path={`/${process.env.APP}/:category?/:screen?/:subscreen?/:id?/:section?`}
                render={(props) => (
                    <App
                        {...props}
                    />
                )}
            />
        </div>
    );

    initAnalytics('UA-111307782-1');

// you should only use `withAnalytics` once to wrap your whole app
    const App = withRouter(withAnalytics(Root));

    const AppWithRouter = () => (
        <HashRouter>
            <App />
        </HashRouter>
    );

    ReactDOM.render(<AppWithRouter />, document.getElementById('main'));
}
```

**Comment by sonaye** [comment]
Does it work when you do `const App = Root;`? can you debug that?
